# config to perform customised tracking


overwrite: 0
restart_checkpoints: 0

data_directory: /work/bb1153/b382635/data/final_tracks
results_directory: /work/bb1153/b382635/data/track_statistics
# checkpoint_directory: /scratch/b/b382635/analysis_checkpoints
checkpoint_directory: /work/bb1153/b382635/data/track_statistics

region: amazon
version: updraft_ice_only

start_date: '2021-07-01 00:00:00' # [ALSO NEEDS SETTING IN .SH]
end_date: '2021-07-08 00:00:00' # [ALSO NEEDS SETTING IN .SH]

# which sets of statistics would you like to calculate
results:
  first:
    name: first_bucket
    shortname: first
    function: FirstBucket
    parameters: 
       overall: False # parameters to pass to funciton call
    use_stats: False # whether to use the statistics from the first buckets
  focus:
    name: focus_bucket
    shortname: fcs
    function: FocusBucketAC
    parameters: False # parameters to pass to funciton call
    use_stats: False # whether to use the statistics from the first buckets
  # cross_section:
  #   name: cross_section
  #   shortname: cross
  #   function: CrossSection
  #   parameters: 
  #     variables: ['anvil_iwp',] # variables to get cross sections of
  #   use_stats: True # whether to use the statistics from the first buckets

batch_size: 4 # number of time steps to process at once

# for system-wise analysis
batch_system: 16 # number of systems to process at once
system_wise_version: 'fcsfirst' # sets results directory and how to filter valid systems
# max_system_size: 50000 # (pixels) maximum size of a system to process
max_system_domain: 0.5 # (proportion) maximum proportion of the dmonain allowed to be occupied at systems largest extent
start_idx: 0 # (cloud number, out of remaining) where to start from
